services:
  blog-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php
    user: "1001:1001"
    ports:
      - "80:80"
    volumes:
      - ./app:/opt/app
    environment:
      - PHP_IDE_CONFIG=serverName=blog-app
    restart: unless-stopped
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
