services:
  init_permissions:
    image: busybox 
    volumes:
      - logs_volume:/logs
      - cache_volume:/cache
    command: chmod -R 775 /logs && chmod -R 775 /cache
  blog-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./app:/opt/app
      - cache_volume:/opt/app/cache
      - logs_volume:/opt/app/logs
    environment:
      - PHP_IDE_CONFIG=serverName=blog-app
    restart: unless-stopped
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  cache_volume:    
  logs_volume:
