<?php

namespace ContainerMsO4VjT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParsedownExtraService extends App_Kernel_KernelDevDebugContainer
{
    /**
     * Gets the public 'ParsedownExtra' shared autowired service.
     *
     * @return \ParsedownExtra
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 2).'/vendor/erusev/parsedown/Parsedown.php';
        include_once \dirname(__DIR__, 2).'/vendor/erusev/parsedown-extra/ParsedownExtra.php';

        return $container->services['ParsedownExtra'] = new \ParsedownExtra();
    }
}
