# Конфигурация сервисов
services:
    # Конфигурация по умолчанию для сервисов в папке src/
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Регистрируем все контроллеры как публичные сервисы
    App\Controller\:
        resource: '../src/Controller/'
        public: true
        tags: ['controller.service_arguments']

    # Регистрируем все сервисы
    App\Service\:
        resource: '../src/Service/'

    # Регистрируем все интерфейсы
    App\Interfaces\:
        resource: '../src/Interfaces/'

    # Явно регистрируем BlogService как реализацию BlogInterface
    App\Interfaces\BlogInterface:
        alias: App\Service\BlogMarkdownService

    # Регистрируем Twig как сервис
    Twig\Environment:
        arguments:
            $loader: '@Twig\Loader\FilesystemLoader'
        calls:
            - method: setCache
              arguments: ['%kernel.cache_dir%/twig']
            - method: enableDebug
              arguments: [true]
            - method: enableAutoReload
              arguments: [true]

    Twig\Loader\FilesystemLoader:
        arguments:
            $paths: ['%kernel.project_dir%/templates'] 