<?php

namespace ContainerWW3zHif;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerService extends App_Kernel_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BlogController' shared autowired service.
     *
     * @return \App\Controller\BlogController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 2).'/src/Controller/BlogController.php';
        include_once \dirname(__DIR__, 2).'/src/Interfaces/BlogInterface.php';
        include_once \dirname(__DIR__, 2).'/src/Service/BlogService.php';
        include_once \dirname(__DIR__, 2).'/vendor/twig/twig/src/Environment.php';
        include_once \dirname(__DIR__, 2).'/vendor/twig/twig/src/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 2).'/vendor/twig/twig/src/Loader/FilesystemLoader.php';

        $a = new \Twig\Environment(new \Twig\Loader\FilesystemLoader([(\dirname(__DIR__, 2).'/templates')]));
        $a->setCache(($container->targetDir.''.'/twig'));
        $a->enableDebug(true);
        $a->enableAutoReload(true);

        return $container->services['App\\Controller\\BlogController'] = new \App\Controller\BlogController(new \App\Service\BlogService(), $a);
    }
}
