<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEWkytkt\App_Kernel_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEWkytkt/App_Kernel_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEWkytkt.legacy');

    return;
}

if (!\class_exists(App_Kernel_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEWkytkt\App_Kernel_KernelDevDebugContainer::class, App_Kernel_KernelDevDebugContainer::class, false);
}

return new \ContainerEWkytkt\App_Kernel_KernelDevDebugContainer([
    'container.build_hash' => 'EWkytkt',
    'container.build_id' => 'b3d22c55',
    'container.build_time' => 1753795344,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEWkytkt');
