<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxhTTUB\App_Kernel_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxhTTUB/App_Kernel_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxhTTUB.legacy');

    return;
}

if (!\class_exists(App_Kernel_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxhTTUB\App_Kernel_KernelDevDebugContainer::class, App_Kernel_KernelDevDebugContainer::class, false);
}

return new \ContainerZxhTTUB\App_Kernel_KernelDevDebugContainer([
    'container.build_hash' => 'ZxhTTUB',
    'container.build_id' => 'f9e57d08',
    'container.build_time' => 1753879466,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxhTTUB');
