<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    return;
}

require dirname(__DIR__, 1).'/vendor/autoload.php';
(require __DIR__.'/App_Kernel_KernelDevDebugContainer.php')->set(\ContainerAdo8e8F\App_Kernel_KernelDevDebugContainer::class, null);
require __DIR__.'/ContainerAdo8e8F/getBlogControllerService.php';

$classes = [];
$classes[] = 'App\Controller\BlogController';
$classes[] = 'App\Service\BlogService';
$classes[] = 'Twig\Environment';
$classes[] = 'Twig\Loader\FilesystemLoader';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

$preloaded = Preloader::preload($classes);
