<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsO4VjT\App_Kernel_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsO4VjT/App_Kernel_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMsO4VjT.legacy');

    return;
}

if (!\class_exists(App_Kernel_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMsO4VjT\App_Kernel_KernelDevDebugContainer::class, App_Kernel_KernelDevDebugContainer::class, false);
}

return new \ContainerMsO4VjT\App_Kernel_KernelDevDebugContainer([
    'container.build_hash' => 'MsO4VjT',
    'container.build_id' => '55fdc7f8',
    'container.build_time' => 1753910760,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsO4VjT');
